name: Commit Notification

on:
  push:
    branches: [ main ]

jobs:
  Notify:
    runs-on: ubuntu-latest
    name: Send Notification
    steps:
      - name: Send Notification
        uses: Retr0-01/better-discord-notification@main
        with:
          webhook-url: ${{ secrets.CI_DISCORD_WEBHOOK }} # It is recommended to store your webhooks using actions secrets
          msg-content: 'A new commit has been pushed to C-Spire-Gaming/workflows'
          embed-color: '3093151'
          ignore-hidden: 'false'