name: 'Update Issue with Default Date and Time'

on:
  issues:
    types: [opened]

jobs:
  update-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check and Update Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const now = new Date();
            const currentDate = now.toISOString().split('T')[0]; // YYYY-MM-DD
            const currentTime = now.toTimeString().split(' ')[0].substring(0, 5); // HH:MM

            // Define regex patterns to match placeholders and check if the date and time are missing
            const datePattern = /- \*\*Date\*\*: \{(\d{4}-\d{2}-\d{2})\}/;
            const timePattern = /- \*\*Time\*\*: \{(\d{2}:\d{2})\}/;

            // Check if placeholders are found and missing
            const isDateMissing = !datePattern.test(issueBody);
            const isTimeMissing = !timePattern.test(issueBody);

            let updatedBody = issueBody;

            // Replace missing date with the current date
            if (isDateMissing) {
              updatedBody = updatedBody.replace(/- \*\*Date\*\*: \{.*?\}/, `- **Date**: ${currentDate}`);
            }

            // Replace missing time with the current time
            if (isTimeMissing) {
              updatedBody = updatedBody.replace(/- \*\*Time\*\*: \{.*?\}/, `- **Time**: ${currentTime}`);
            }

            // Update the issue if necessary
            if (updatedBody !== issueBody) {
              await github.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: updatedBody
              });
            }